# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: GitDownloader@0
  inputs:
    RepositoryUrl: 'https://github.com/ntthaibk/sample-ci-cd-azure.git'
    BranchTag: 'master'

- script: docker pull katalonstudio/katalon
  displayName: 'Pull katalon studio images'
  
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
  displayName: 'Runnning Katalon TS_RegressionTest'